### PR TITLE
Add security by token and optional domain

### PR DESCRIPTION
**Pull request by gmarsay**
**Access list**
The parameter "ACCESS_LIST" is now optional, lgproxy accept all connections if not configured.

**Security token**
Add optional parameter "SECURITY_TOKEN" in lg.cfg and lgproxy.cfg to secure connection between lg and lgproxy.

The parameter must be secret and can be cumulated with "ACCESS_LIST".

**Optional domain**
The parameter "DOMAIN" (in lg.cfg) is now optional. This change permit to resolves container names without a domain, and have different proxy from different domains.

### CODE REVIEW

**Comment by zorun** [comment]
Making `DOMAIN` optional is fine, can you submit it separately? I will merge it straight away.

The security token looks interesting. Can you share what kind of problems it solves? Is that intended as an additional protection, or to simplify configuration?

I think I would prefer "shared secret" instead of "security token". The security of bird-lg is not very good in the first place (e.g. frontend-backend communication is using plain HTTP), and using "security" tokens may give the false impression that it becomes more secure. Also, this is a bit different from usual "API tokens".

As for the access list, judging from the code, it looks like it is already optional?

**Comment by gmarsay** [comment]
Hi zorun, 

The feature "optional domain" is now separate in PR #68.

For the security_token/shared_secret, this is useful for replace access_list when bird is in a Docker container with non fix ip address. I will propose another PR after validation of #68.

Currently, the "ACCESS_LIST" parameter isn't really optional because if app.config["ACCESS_LIST"] in lgproxy.py (line 58).

**Comment by zorun** [comment]
Ok, actually, in the current code, an empty list `ACCESS_LIST`means that any IP is allowed.

I would prefer to keep it this way to protect against configuration errors. For instance, if there is a typo (`ACCES_LIST` instead of `ACCESS_LIST`), the current code will crash, which is a good thing. With your change, it would silently accept any IP.

What you can do is document this behaviour (add a comment in the config file)

Feel free to either open a new PR or force-push on this one.

**Comment by gmarsay** [comment]
Implementation of SHARED_SECRET in PR #71

**Comment by zorun** [comment]
Let's move the discussion to the new pull request. It should work if you set ACCESS_LIST to an empty list.

**Pull request closed without merging**
